baseurl = "https://kevinsahin.com/"
languageCode = "en-US"
title = "Kevin Sahin"
# Enable comments by entering your Disqus shortname
disqusShortname = "kevinsahin-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-124546758-1"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile_pic_400x400.jpg"
  author = "Kevin Sahin"
  description = "Kevin Sahin's personnal blog - I talk about running about running a bootstrapped software business and tech. "

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "sahin.kevin@gmail.com"
  Twitter       = "sahinkevin"
  LinkedIn      = "kevin-sahin-89700586"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
